# Site settings
title:       fresheyeball
email:       fresheyeball@gmail.com
author:      Isaac Shapira
description: "I will publish content on this thing regularly. For realz... This is not going to be another dead blog roll. Not this time. No."
baseurl:     ""
url:         "http://blog.fresheyeball.com"

# Google analytics
google_analytics: UA-60318654-1

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Social icons
show_social_icons: false
github_username: fresheyeball
stackoverflow_id: fresheyeball
twitter_username: fresheyeball
google_plus_id:
linkedin_username:
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
markdown:     redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     3
sass:
  compressed: true
